# Generated by Django 4.0.3 on 2022-04-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
