# Generated by Django 4.0.3 on 2022-05-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_images_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Cp',
        ),
    ]
