# Generated by Django 4.0.3 on 2022-05-11 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_alter_postreact_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreact',
            name='loved_by',
        ),
        migrations.AddField(
            model_name='postreact',
            name='loved_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
