# Generated by Django 4.0.3 on 2022-05-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_alter_postreact_loved_by_alter_postreact_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreact',
            name='loved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
