# Generated by Django 4.0.3 on 2022-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sleep_time', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('total_sleep', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
