# Generated by Django 4.0.3 on 2022-05-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_sleeptime_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleeptime',
            old_name='total_sleep',
            new_name='total_sleep_hour',
        ),
        migrations.AddField(
            model_name='sleeptime',
            name='total_sleep_min',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
