# Generated by Django 4.0.3 on 2022-03-30 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='NewsImages/')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('frontend_app_name', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='Tools/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Fitness', 'Fitness'), ('Technology', 'Technology'), ('Daily', 'Daily'), ('Others', 'Others')], default='Technology', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='NewsImages/')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.news')),
            ],
        ),
    ]
